[workspace]
resolver = "3"
members = [
    "basics",
    "concepts",
    "utils",
    "basics/src/rust_lang/packages_crates_modules",
    "basics/src/rust_lang/automated_tests",
    "basics/src/rust_lang/my_crate",
    "basics/src/rust_lang/adder",
]
