[package]
name = "concepts"
version = "0.1.0"
edition = "2024"
default-run = "concurrency"

[dependencies]
futures = "0.3.31"

[[bin]]
name = "core"
path = "src/core/runner.rs"

[[bin]]
name = "concurrency"
path = "src/concurrency/runner.rs"